# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/v1/docs.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# Swagger UI
app.swagger_ui:
    path: /api/v1/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
